// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'numContainer': string;
  'pageNum': string;
  'reverse': string;
  'root': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
