// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'poster': string;
  'props': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
