// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'any': string;
  'notification': string;
  'show': string;
  'showNotification': string;
}
export const cssExports: CssExports;
export default cssExports;
